### ISSUE TITLE
MsTest option

### ISSUE THREAD

**Issue by litkod** [gocd-contrib/xunit-converter-task#8]
Hi, there are no **MsTest** option to choose from the "Converter Type" dropdown (during Add new XUnit Converter task). Only JsUnit and Nose options available. Anything I've missed out?

I am using xunit-converter-task-1.1.jar on Go Version 16.1.0.
Jar gotten from https://github.com/gocd-contrib/xunit-converter-task/releases

**Comment by arvindsv** [comment]
I think the bundled version of gocd-contrib/xunit-converter is not the latest. @srinivasupadhya should know.

**Comment by sekberg37** [comment]
The same thing happened to me where I did not see mstest in the bundled 1.1. I was able to build xunit-converter (https://github.com/gocd-contrib/xunit-converter), but I had to update the pom.xml file due to onejar-maven-plugin being deprecated. After that I built xunit-converter-task

After I did a local build I am now able to see mstest in the UI so the released jar for 1.1 is not the latest code. Also, I haven't gotten the plug-in to work with my mstest or vstest.console.exe trx reports. The plug-in does work with the test trx files in xunit-converter though.

From what I can tell it looks like the mstest aspect of the plug-in was written for the vstest.console.exe flavor of trx files, but it is missing some aspect to support the trx files that my vstest.console.exe tests generate.

Also, I just discovered that gocd version 17.2.0 has removed the API that this plug-in uses on 2/17/2017. So the last version this plug-in works with is 17.1.0. GoCD has moved from a java plug-in API to a JSON based API. https://developer.gocd.io/17.5.0/writing_go_plugins/overview.html

**Comment by arvindsv** [comment]
Is this related to https://github.com/gocd-contrib/xunit-converter/pull/7?

**Comment by sekberg37** [comment]
Yes @arvindsv gocd-contrib/xunit-converter#7 fixes the build issue that I encountered.

**Comment by arvindsv** [comment]
Ok, that's merged and a new release of this plugin is out (https://github.com/gocd-contrib/xunit-converter-task/releases/tag/1.2).
